
#include<bits/stdc++.h>
#define ll  int64_t
#define pp pair<double,char>
#define ppn pair<pp,int>
#define F first
#define S second

using namespace std;



int main()
{

    string s = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    string plaintext = "VDUMU NEC E NEFF EDUEY SV ZUOEH DSOD SH VDU ESM EHY URVUHYUY BKNEMY LBV LI CSODV SV NEC MSYYFUY NSVD DLFUC VDEV NUMU VDU GLBVDC LI VBHHUFC OEEF'C VERS GLAUY VLNEMY LHU, VDUH KFBHOUY SHVL SV ILM E GLGUHV OEEF NLHYUMUY SYFP DLN DSC YMSAUM TLBFY KSTX LBV LHU EGLHO CL GEHP VDUMU NEC HLN LHFP ZFETXHUCC NSVD HLVDSHO ZBV VDU KECV-IFECDSHO LI E TLFLMUY CSOHEF FSODV VL MUFSUAU VDU OFLLG VDU ESM NEC IBFF LI E MBCDSHO CLBHY OEEF FUEHUY ILMNEMY EOESHCV YUTUFUMEVSLH VDUH EHY VDU VERS KLKKUY LBV LI VDU VBHHUF EHY YUCTUHYUY VL OMLBHY-FUAUF LHTU GLMU VDU FBRLM DLVUF CESY VDU YMSAUM BHHUTUCCEMSFP DU DUFKUY OEEF NSVD DSC ZEOOEOU ETTUKVUY E VUHVD-TMUYSV VSK NSVD E ZBCSHUCCFSXU ESM KSTXUY BK E NESVSHO KECCUHOUM EHY NEC MSCSHO EOESH SH EFF VDSC IMLG VDU GLGUHV LI YUZEMXEVSLH VDUMU DEY ZUUH HL OFSGKCU LI CXP VMEHVLM EV VDU ZUOSHHSHO LI VDU VDSMVUUHVD GSFFUHHSBG VDSC VUHYUHTP MUETDUY SVC TFSGER EC VDU TUHVUM LI VDU SGKUMSEF OLAUMHGUHV ILM BHZMLXUH DBHYMUYC LI OUHUMEVSLHC EHY FLTEVUY EC SV NEC VLNEMY VDU TUHVMEF MUOSLHC LI VDU OEFERP EGLHO VDU GLCV YUHCUFP KLKBFEVUY EHY SHYBCVMSEFFP EYAEHTUY NLMFYC LI VDU CPCVUG, SV TLBFY CTEMTUFP DUFK ZUSHO VDU YUHCUCV EHY MSTDUCV TFLV LI DBGEHSVP VDU METU DEY UAUM CUUH SVC BMZEHSQEVSLH, KMLOMUCCSHO CVUEYSFP DEY ISHEFFP MUETDUY VDU BFVSGEVU. EFF VDU FEHY CBMIETU LI VMEHVLM CJBEMU GSFUC SH URVUHV NEC E CSHOFU TSVP VDU KLKBFEVSLH EV SVC DUSODV NEC NUFF SH URTUCC LI ILMVP ZSFFSLHC VDSC UHLMGLBC KLKBFEVSLH NEC YUALVUY EFGLCV UHVSMUFP VL VDU EYGSHSCVMEVSAU HUTUCCSVSUC LI UGKSMU EHY ILBHY VDUGCUFAUC EFF VLL IUN ILM VDU TLGKFSTEVSLHC LI VDU VECX (SV SC VL ZU MUGUGZUMUY VDEV VDU SGKLCCSZSFSVP LI KMLKUM EYGSHSCVMEVSLH LI VDU OEFETVST UGKSMU BHYUM VDU BHSHCKSMUY FUEYUMCDSK LI VDU FEVUM UGKUMLMC NEC E TLHCSYUMEZFU IETVLM SH VDU IEFF) YESFP IFUUVC LI CDSKC SH VDU VUHC LI VDLBCEHYC ZMLBODV VDU KMLYBTU LI VNUHVP EOMSTBFVBMEF NLMFYC VL VDU YSHHUM VEZFUC LI VMEHVLM SVC YUKUHYUHTU BKLH VDU LBVUM NLMFYC ILM ILLY EHY SHYUUY ILM EFF HUTUCCSVSUC LI FSIU GEYU VMEHVLM SHTMUECSHOFP ABFHUMEZFU VL TLHJBUCV ZP CSUOU SH VDU FECV GSFFUHHSBG LI VDU UGKSMU VDU GLHLVLHLBCFP HBGUMLBC MUALFVC GEYU UGKUMLM EIVUM UGKUMLM TLHCTSLBC LI VDSC EHY SGKUMSEF KLFSTP ZUTEGU FSVVFU GLMU VDEH VDU KMLVUTVSLH LI VMEHVLM'C YUFSTEVU WBOBFEM AUSH";
    string key = "VUSHALMNFQPORWGYZXICETJKDB";


    map<char,double>maps;


    int k = 9, l=0;
    //Calculating Frequency
    for(int i=0; i<plaintext.length(); i++){

        if(plaintext[i]>='A' && plaintext[i]<='Z')
        {
            maps[plaintext[i]]++;
            l++;
        }

    }

    vector<pp>v;
    for(int i=0; i<26; i++)
    {

        maps[s[i]]=(100.0*maps[s[i]])/l;

       v.push_back({maps[s[i]],s[i]});
    }
    sort(v.rbegin(),v.rend());


    for(int i=0; i<12; i++){
    cout<<fixed<<setprecision(2)<<v[i].S<<"  \t"<<v[i].F<<"%\t\t\t";
     cout<<fixed<<setprecision(2)<<v[i+13].S<<"  \t"<<v[i+13].F<<"%"<<endl;
    }
    cout << "\n" << endl;

    //Decyption
    for(int i=0; i<plaintext.length(); i++){
        if(plaintext[i]>='A' && plaintext[i]<='Z')
        {
            int x = plaintext[i]-'A';
            cout<<key[x];


        }
        else cout<<plaintext[i];

    }

}



